feat(DO-779): First version of module
dodevops/terraform-azure-storage pull request #1
Opened 2021-10-11 14:40 UTC by timdeluxe

2021-11-10 13:27 UTC, dploeger approved these changes
Thanks! 🎁

2021-11-15 10:10 UTC, ThomasMinor requested changes

2021-11-15 10:10 UTC, ThomasMinor commented on output.tf
> +
Remove superfluous blank line

2021-11-15 10:47 UTC, ThomasMinor approved these changes
👍

2021-11-15 10:48 UTC, merged